import type { Metadata } from "next";
import Link from "next/link";
import { buttonVariants } from "@/components/ui/button";
import { PRODUCER_CONSOLE } from "@/lib/site";

export const metadata: Metadata = {
  title: "Producer sign in",
  description: "Producer sign-in has moved to producers.counterscent.com.",
};

/**
 * SIGN-IN HAS MOVED OFF THIS SITE. This page is the hand-off that keeps the
 * URL alive.
 *
 * Two reasons it is no longer the sign-in screen itself.
 *
 * 1. It cannot be one. Authentication needs a server, a session and a
 *    database. This project is a static export with none of those and is
 *    staying that way, so the console lives on its own origin
 *    (HANDOFF.md, "The architecture answer"), and that is where the real
 *    sign-in screen now is.
 *
 * 2. What was here was a live <input> that threw away what you typed. It
 *    said so afterwards, in a panel that appeared on submit, which is better
 *    than a fake success and still worse than not having the field. The
 *    replacement on the console origin renders the same screen with every
 *    control structurally disabled and the reason stated before you reach
 *    it, rather than after.
 *
 * NOT DELETED, and not a redirect. `public/_redirects` is generated by
 * scripts/generate-redirects.mjs from the affiliate link map, so adding a
 * rule to it is a change to that generator rather than to this route. A
 * visible hand-off also tells a producer something true and useful: the
 * console is at a different address. `components/producers/login-form.tsx`
 * is left in place unreferenced; it is the source the Worker's sign-in
 * screen was written from and deleting it now would lose that trail.
 */
export default function ProducerLoginPage() {
  return (
    <div className="container py-14 sm:py-20">
      <div className="mx-auto flex max-w-[52ch] flex-col gap-6">
        <div className="flex flex-col gap-3">
          <h1 className="font-display text-fluid-h2">Producer sign in has moved</h1>
          <p className="text-muted-foreground">
            Producer accounts, listings and the review queue live on their own address:{" "}
            <span className="font-semibold text-foreground/85">producers.counterscent.com</span>
            . This part of the site is the public catalogue and has no accounts in it.
          </p>
        </div>

        <div className="rounded-frame border border-dashed border-border p-6">
          <h2 className="font-display text-lg">Still not open</h2>
          <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
            Moving address did not make it work. There are no producer accounts anywhere
            yet, nothing to sign in to, and no submission can be stored. The console shows
            the screens as they will be and says at each one what is missing.
          </p>
        </div>

        <div className="flex flex-wrap gap-3">
          <a
            href={`${PRODUCER_CONSOLE}/sign-in`}
            className={buttonVariants({ variant: "default" })}
          >
            Go to producer sign in
          </a>
          <Link href="/producers" className={buttonVariants({ variant: "outline" })}>
            How the programme works
          </Link>
        </div>

        <p className="text-sm text-muted-foreground">
          Here to compare fragrances instead?{" "}
          <Link href="/dupe-finder" className="underline underline-offset-2 hover:text-primary">
            The Dupe Finder
          </Link>{" "}
          needs no account and never will.
        </p>
      </div>
    </div>
  );
}
