/**
 * GENERATED FILE — do not edit by hand.
 *
 * Written by scripts/generate-listing-dates.mjs. Read
 * lib/listing-dates.ts for what the date means and why it is "first live"
 * rather than "approved" or "submitted".
 *
 * COMMITTED ON PURPOSE, and not regenerated by `prebuild`. These dates come
 * from git history, and Cloudflare's builder does not guarantee a full clone —
 * deriving them in CI would produce dates that are right locally and silently
 * wrong in production. The build reads this file and nothing else.
 *
 * Dates are write-once: re-running the script preserves every entry it already
 * finds here. Use --rebuild to re-derive from history deliberately.
 *
 * A listing missing from this map is NOT an error. It renders everywhere as
 * normal and is simply excluded from the "recently added" surface, because
 * the alternative — guessing a date — is a fabricated fact on a page whose
 * whole claim is that it does not fabricate.
 */

/** Listing slug → ISO date (YYYY-MM-DD) of the commit that first put it live. */
export const LISTING_FIRST_LIVE: Record<string, string> = {
  "afnan-embassy-royal-extrait": "2026-09-02",
  "afnan-supremacy-not-only-intense": "2026-09-02",
  "ard-al-zaafaran-bint-hooran": "2026-09-02",
  "armaf-club-de-nuit-intense-man": "2026-09-02",
  "armaf-club-de-nuit-sillage": "2026-09-02",
  "armaf-club-de-nuit-urban-man": "2026-09-02",
  "fragrance-world-barakkat-rouge-540": "2026-09-02",
  "fragrance-world-mocha-wood": "2026-09-02",
  "french-avenue-royal-blend-extrait": "2026-09-02",
  "lattafa-al-areeq-gold": "2026-09-02",
  "lattafa-ana-abiyedh-rouge": "2026-09-02",
  "lattafa-asad": "2026-09-02",
  "lattafa-khamrah": "2026-09-02",
  "lattafa-khamrah-qahwa": "2026-09-02",
  "lattafa-maahir-black-edition": "2026-09-02",
  "lattafa-mayar-cherry-intense": "2026-09-02",
  "lattafa-oud-for-glory": "2026-09-02",
  "lattafa-qaed-al-fursan-unlimited": "2026-09-02",
  "lattafa-velvet-oud": "2026-09-02",
  "lattafa-velvet-rose": "2026-09-02",
  "maison-alhambra-jean-lowe-matiere": "2026-09-02",
  "maison-alhambra-leonie": "2026-09-02",
  "maison-alhambra-maitre-de-blue": "2026-09-02",
  "maison-alhambra-sceptre-amazonite": "2026-09-02",
  "rasasi-hawas-black": "2026-09-02",
  "ard-al-zaafaran-oud-orchid": "2026-09-03",
  "fragrance-world-neroli-riviera": "2026-09-03",
  "fragrance-world-vanille-en-tobacco": "2026-09-03",
  "lattafa-ameer-al-oudh-intense-oud": "2026-09-03",
  "lattafa-mohra": "2026-09-03",
  "lattafa-qaed": "2026-09-03",
  "zimaya-oud-is-great": "2026-09-03",
  "aromapassions-admire": "2026-09-04",
  "aromapassions-bittersweet": "2026-09-04",
  "aromapassions-blooming": "2026-09-04",
  "aromapassions-erotic": "2026-09-04",
  "aromapassions-freedom": "2026-09-04",
  "aromapassions-glamorous": "2026-09-04",
  "aromapassions-heavenly": "2026-09-04",
  "aromapassions-masculinity": "2026-09-04",
  "aromapassions-mystical": "2026-09-04",
  "aromapassions-revive": "2026-09-04",
  "aromapassions-sensual": "2026-09-04",
  "aromapassions-spark": "2026-09-04",
  "aromapassions-sparkle": "2026-09-04",
  "aromapassions-virility": "2026-09-04",
  "the-clone-brave-in-love-no-37": "2026-09-04",
  "the-clone-brutal-story-no-73": "2026-09-04",
  "the-clone-lady-on-fire-no-23": "2026-09-04",
  "the-clone-naked-cherry-no-33": "2026-09-04",
  "the-clone-pleasure-noir-no-63": "2026-09-04",
  "the-clone-rouge-veil-no-13": "2026-09-04",
  "the-clone-thunderstorm-no-93": "2026-09-04",
  "the-clone-ultimatum-no-53": "2026-09-04",
  "the-clone-whisper-no-43": "2026-09-04",
  "aromapassions-adventure": "2026-09-05",
  "aromapassions-audacious": "2026-09-05",
  "aromapassions-beauty": "2026-09-05",
  "aromapassions-blossom": "2026-09-05",
  "aromapassions-bold": "2026-09-05",
  "aromapassions-captivate": "2026-09-05",
  "aromapassions-charisma": "2026-09-05",
  "aromapassions-clarity": "2026-09-05",
  "aromapassions-cool": "2026-09-05",
  "aromapassions-delight": "2026-09-05",
  "aromapassions-femininity": "2026-09-05",
  "aromapassions-fiery": "2026-09-05",
  "aromapassions-glimmer": "2026-09-05",
  "aromapassions-harmony": "2026-09-05",
  "aromapassions-intense": "2026-09-05",
  "aromapassions-legendary": "2026-09-05",
  "aromapassions-luminous": "2026-09-05",
  "aromapassions-luxurious": "2026-09-05",
  "aromapassions-mesmorize": "2026-09-05",
  "aromapassions-nature": "2026-09-05",
  "aromapassions-precious": "2026-09-05",
  "aromapassions-robust": "2026-09-05",
  "aromapassions-sweet": "2026-09-05",
  "aromapassions-uplifting": "2026-09-05",
};
